create table "public"."visit" (
    "id" bigint generated by default as identity not null,
    "link_id" bigint not null,
    "browser" text,
    "os" text,
    "referrer" text,
    "ip" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."visit" enable row level security;

CREATE UNIQUE INDEX visit_pkey ON public.visit USING btree (id);

alter table "public"."visit" add constraint "visit_pkey" PRIMARY KEY using index "visit_pkey";

alter table "public"."visit" add constraint "visit_link_id_fkey" FOREIGN KEY (link_id) REFERENCES link(id) not valid;

alter table "public"."visit" validate constraint "visit_link_id_fkey";


